(() => {
  const K = window.K;
  K.EN = {
    gruppen: {
      "Unterwegs": "On the move", "Alltag": "Everyday", "Gefühle": "Feelings", "Tanz & Musik": "Dance & music",
      "Sport & Akrobatik": "Sport & acrobatics", "Arbeit & Nerd": "Work & nerd stuff", "Essen & Trinken": "Food & drink",
      "Gaming": "Gaming", "Schlaf & Ruhe": "Sleep & rest", "Wetter & Natur": "Weather & nature", "Magie & Glitch": "Magic & glitch",
      "Im Gespräch": "In conversation", "Farben & Muster": "Colors & patterns", "Kopf": "Headwear", "Augen": "Eyewear",
      "Gesicht": "Face", "Hals": "Neck", "Kleidung": "Outfits"
    },
    namen: {
      "Spazieren": "Stroll", "Wandern mit Stock": "Hike with stick", "Schleichen": "Sneak", "Hüpfen": "Hop", "Moonwalk": "Moonwalk",
      "Stolpern": "Trip over", "Rennen": "Run", "Seitwärts trippeln": "Side shuffle", "Joggen": "Jog", "Marschieren": "March",
      "Watscheln": "Waddle", "Kriechen": "Crawl", "Klettern": "Climb", "Abseilen": "Abseil", "Schwimmen": "Swim", "Tauchen": "Dive",
      "Propellerflug": "Propeller flight", "Ballonfahrt": "Balloon ride", "Schirmflug": "Umbrella glide", "Skateboard": "Skateboard",
      "Surfen": "Surf", "Teleportieren": "Teleport", "Reinsprinten": "Sprint in", "Rumstehen": "Idle", "Umschauen": "Look around",
      "Winken": "Wave", "Beidhändig winken": "Double wave", "Strecken": "Stretch", "Gähnen": "Yawn", "Am Kopf kratzen": "Head scratch",
      "Niesen": "Sneeze", "Hinsetzen": "Sit down", "Auf dem Rücken liegen": "Lie on back", "Hände in die Hüften": "Hands on hips",
      "Warten und tippen": "Foot tap", "Fegen": "Sweep", "Wischen": "Mop", "Blumen giessen": "Water the plants", "Paket tragen": "Carry a parcel",
      "Handy scrollen": "Doomscroll", "Selfie": "Selfie", "Zeitung lesen": "Read the paper", "Einkaufen": "Shopping", "Freuen": "Cheer",
      "Lachen": "Laugh", "Kichern": "Giggle", "Verliebt": "In love", "Traurig": "Sad", "Weinen": "Cry", "Wütend": "Angry", "Ausrasten": "Meltdown",
      "Genervt": "Annoyed", "Verlegen": "Shy", "Stolz": "Proud", "Erschrecken": "Startled", "Verwirrt": "Confused", "Nachdenken": "Ponder",
      "Idee": "Idea", "Müde": "Tired", "Gelangweilt": "Bored", "Schmollen": "Sulk", "Überrascht": "Surprised", "Schulterzucken": "Shrug",
      "Headbangen": "Headbang", "Disco": "Disco", "Robotertanz": "Robot dance", "Wackeltanz": "Wiggle", "Floss": "Floss", "Dab": "Dab",
      "Breakdance": "Breakdance", "Pirouette": "Pirouette", "Gitarre spielen": "Guitar", "Auflegen": "DJ set", "Trompete": "Trumpet",
      "Klavier": "Piano", "Singen": "Sing", "Dirigieren": "Conduct", "Musik hören": "Vibe to music", "Gruppentanz": "Line dance",
      "Konfettiparty": "Confetti party", "Hanteln stemmen": "Dumbbell curl", "Kniebeugen": "Squats", "Hampelmann": "Jumping jacks",
      "Salto": "Flip", "Rückwärtssalto": "Backflip", "Rad schlagen": "Cartwheel", "Handstand": "Handstand", "Seilspringen": "Jump rope",
      "Jonglieren": "Juggle", "Dribbeln": "Dribble", "Fussball kicken": "Kick a ball", "Basketball werfen": "Shoot hoops", "Boxen": "Box",
      "Karate": "Karate", "Yoga-Baum": "Tree pose", "Meditieren": "Meditate", "Gewichtheben": "Weightlifting", "Seitlich dehnen": "Side stretch",
      "Tippen": "Type", "Hacken": "Hack", "Auf den Build warten": "Waiting for the build", "Bug gefunden": "Found a bug", "Code-Review": "Code review",
      "Deployen": "Deploy", "Alles brennt": "This is fine", "Kaffeepause": "Coffee break", "Im Meeting": "In a meeting", "Präsentieren": "Present",
      "Notizen machen": "Take notes", "Dateien jonglieren": "Juggle files", "Server streicheln": "Pet the server", "Kabelsalat": "Cable mess",
      "Hämmern": "Hammer", "Schrauben": "Wrench", "Malen": "Paint", "Forschen": "Investigate", "Chemie": "Chemistry",
      "Kaffee schlürfen": "Sip coffee", "Tee trinken": "Tea time", "Pizza essen": "Pizza", "Burger mampfen": "Burger", "Eis schlecken": "Ice cream",
      "Donut": "Donut", "Nudeln schlürfen": "Slurp noodles", "Apfel knabbern": "Munch an apple", "Popcorn": "Popcorn",
      "Kerzen auspusten": "Blow out candles", "Grillen": "Barbecue", "Kochen": "Cook", "Vollgefuttert": "Food coma", "Anstossen": "Cheers",
      "Zocken": "Gaming", "Gewonnen": "Victory", "Rage Quit": "Rage quit", "Rhythmusspiel": "Rhythm game", "VR-Welt": "VR", "Speedrun": "Speedrun",
      "Loot gefunden": "Loot!", "Level Up": "Level up", "Game Over": "Game over", "Respawn": "Respawn", "Schwertkampf": "Sword fight",
      "Anfeuern": "Cheer on", "Einschlafen": "Dozing off", "Schlafen": "Sleep", "Schnarchen": "Snore", "Träumen": "Dream",
      "Nickerchen im Sitzen": "Nap", "Schlafwandeln": "Sleepwalk", "Aufwachen": "Wake up", "Im Bett": "In bed", "Hängematte": "Hammock",
      "Sonnenbaden": "Sunbathe", "Sterne gucken": "Stargazing", "Kuscheltier drücken": "Hug a teddy", "Im Regen stehen": "In the rain",
      "Regenschirm": "Umbrella", "Schneeflocken fangen": "Catch snowflakes", "Schneeballschlacht": "Snowball fight", "Frieren": "Freezing",
      "Hitze": "Heatwave", "Gewitter": "Thunderstorm", "Gegen den Wind": "Against the wind", "Laub rechen": "Rake leaves",
      "Schmetterling jagen": "Chase a butterfly", "An Blume riechen": "Smell a flower", "Vogel auf dem Kopf": "Bird on head",
      "Katze streicheln": "Pet the cat", "Zaubern": "Magic", "Schweben": "Levitate", "Unsichtbar werden": "Vanish", "Glitch": "Glitch",
      "Pixel zerfallen": "Disintegrate", "Wachsen und Schrumpfen": "Grow and shrink", "Klonen": "Clone", "Kristallkugel": "Crystal ball",
      "Feuerball": "Fireball", "Durchs Portal": "Through the portal", "Matrix": "Matrix", "Regenbogen-Aura": "Rainbow aura",
      "Zuhören": "Listening", "Antwort überlegen": "Thinking", "Reden": "Talking", "Mit Händen erklären": "Explaining", "Nicken": "Nod",
      "Kopfschütteln": "Shake head", "Daumen hoch": "Thumbs up", "Flüstern": "Whisper", "Laden": "Loading", "Fehler 404": "Error 404",
      "Klassisch Claude": "Classic", "Pastellrosa": "Pastel pink", "Minze": "Mint", "Himmelblau": "Sky blue", "Lavendel": "Lavender",
      "Zitrone": "Lemon", "Tomate": "Tomato", "Schiefer": "Slate", "Schneeweiss": "Snow white", "Mitternacht": "Midnight", "OLED": "OLED",
      "Gold": "Gold", "Silber": "Silver", "Bronze": "Bronze", "Smaragd": "Emerald", "Rubin": "Ruby", "Saphir": "Sapphire", "Amethyst": "Amethyst",
      "Neonpink": "Neon pink", "Neongrün": "Neon green", "Schokolade": "Chocolate", "Erdbeere": "Strawberry", "Karamell": "Caramel",
      "Wassermelone": "Watermelon", "Tiger": "Tiger", "Kuh": "Cow", "Leopard": "Leopard", "Tarnfarbe": "Camo", "Regenbogen": "Rainbow",
      "Holografisch": "Holographic", "Galaxie": "Galaxy", "Lava": "Lava", "Eis": "Ice", "Geist": "Ghost", "Drahtgitter": "Wireframe",
      "Gameboy": "Retro handheld", "Einheit 01": "Unit 01", "Einheit 02": "Unit 02", "Einheit 00": "Unit 00", "Schweizerkreuz": "Swiss cross",
      "Holz": "Wood", "Marmor": "Marble", "Terminal": "Terminal", "Sonnenuntergang": "Sunset",
      "Wanderhut": "Hiking hat", "Zylinder": "Top hat", "Krone": "Crown", "Zauberhut": "Wizard hat", "Cowboyhut": "Cowboy hat",
      "Piratenhut": "Pirate hat", "Kochmütze": "Chef's hat", "Partyhut": "Party hat", "Propellermütze": "Propeller cap",
      "Mütze rot": "Red beanie", "Mütze grau": "Grey beanie", "Mütze senfgelb": "Mustard beanie", "Mütze tannengrün": "Pine beanie",
      "Cap rot": "Red cap", "Cap blau": "Blue cap", "Cap schwarz": "Black cap", "Cap rückwärts": "Backwards cap", "Heiligenschein": "Halo",
      "Teufelshörner": "Devil horns", "Hasenohren": "Bunny ears", "Katzenohren": "Cat ears", "Fuchsohren": "Fox ears", "Antennen": "Antennae",
      "Blume im Haar": "Flower clip", "Schleife": "Bow", "Kopfhörer": "Headphones", "Kopfhörer weiss": "White headphones",
      "Stirnband rot": "Red headband", "Stirnband Frottee": "Sweatband", "Ninja-Band": "Ninja band", "Bauhelm": "Hard hat",
      "Feuerwehrhelm": "Fire helmet", "Wikingerhelm": "Viking helmet", "Ritterhelm": "Knight helmet", "Raumhelm": "Space helmet",
      "Detektivmütze": "Detective cap", "Baskenmütze": "Beret", "Sombrero": "Sombrero", "Doktorhut": "Graduation cap",
      "Einhorn-Horn": "Unicorn horn", "Pilzhut": "Mushroom cap", "Fischerhut": "Bucket hat", "Weihnachtsmütze": "Santa hat",
      "Blumenkranz": "Flower crown", "Lorbeerkranz": "Laurel wreath", "Hexenhut": "Witch hat", "Kopfverband": "Head bandage",
      "Wuschelhaare braun": "Messy hair, brown", "Irokese grün": "Green mohawk", "Irokese pink": "Pink mohawk",
      "Wuschelhaare blond": "Messy hair, blond", "Matrosenmütze": "Sailor cap", "Tell-Apfel": "William Tell's apple",
      "Sennenkäppi": "Alpine cap", "Drachenhörner": "Dragon horns",
      "Pilotenbrille": "Aviators", "Sonnenbrille": "Sunglasses", "Nerdbrille": "Nerd glasses", "Runde Brille": "Round glasses",
      "Herzbrille": "Heart glasses", "Sternbrille": "Star glasses", "3D-Brille": "3D glasses", "Monokel": "Monocle", "Augenklappe": "Eye patch",
      "Skibrille": "Ski goggles", "Taucherbrille": "Diving mask", "VR-Brille": "VR headset", "Pixel-Brille": "Pixel shades",
      "Steampunk-Brille": "Steampunk goggles", "Cyber-Visier": "Cyber visor", "Nachtsicht": "Night vision",
      "Clownnase": "Clown nose", "Wangenröte": "Blush", "Pflaster": "Band-aid", "Vampirzähne": "Vampire fangs", "Zunge raus": "Tongue out",
      "Fliege schwarz": "Black bow tie", "Fliege rot": "Red bow tie", "Fliege gepunktet": "Polka-dot bow tie", "Krawatte rot": "Red tie",
      "Krawatte blau": "Blue tie", "Krawatte gestreift": "Striped tie", "Schal grün": "Green scarf", "Schal blau": "Blue scarf",
      "Goldkette": "Gold chain", "Perlenkette": "Pearl necklace", "Medaille": "Medal", "Anzug": "Suit", "Smoking": "Tuxedo",
      "Trikot 10": "Jersey No. 10"
    }
  };
  K.en = (x) => K.EN.namen[x.n] || x.n;
  K.enGruppe = (g) => K.EN.gruppen[g] || g;
})();
