(() => {
  const K = window.K;
  K.PROPS = {
    stock: ["NN", "n.", "n.", "n.", "n.", "n.", "n.", "n.", "n."],
    leiter: ["n..n", "nnnn", "n..n", "n..n", "nnnn", "n..n", "n..n", "nnnn", "n..n", "n..n", "nnnn", "n..n", "n..n", "nnnn", "n..n", "n..n", "nnnn", "n..n", "n..n", "nnnn", "n..n", "n..n", "nnnn", "n..n", "n..n", "nnnn", "n..n", "n..n", "nnnn", "n..n", "n..n", "nnnn", "n..n", "n..n", "nnnn", "n..n"],
    jetpack: ["SS................SS", "Ss................sS", "SS................SS", "Ss................sS", "SS................SS", ".r................r."],
    ballon: ["..rrr..", ".rrrrr.", ".rrWrr.", ".rrrrr.", "..rrr..", "...r...", "...k...", "..k....", "...k...", "..k....", "...k..."],
    ballonB: ["..bbb..", ".bbbbb.", ".bbWbb.", ".bbbbb.", "..bbb..", "...b...", "...k...", "..k....", "...k...", "..k....", "...k..."],
    schirm: ["....kkkk....", "..kbbbbbbk..", ".kbbbbbbbbk.", "kbbbbbbbbbbk", "k.k..k..k..k", ".....k......", ".....k......", ".....k......", ".....k......", ".....kk....."],
    schirmR: ["....kkkk....", "..krrrrrrk..", ".krrwrrwrrk.", "krrrrrrrrrrk", "k.k..k..k..k", ".....k......", ".....k......", ".....k......", ".....k......", ".....kk....."],
    skateboard: [".NNNNNNNNNNNNNN.", "..kk........kk.."],
    surfbrett: ["..cccccccccccccc..", ".bbbbbbbbbbbbbbbbb", "..bbbbbbbbbbbbbb.."],
    stirnband: ["rrrrrrrrrrrrrr", "............rr", "............r."],
    propeller: [["..yyyyyyyy..", ".....kk.....", "...rrbbrr...", "..rrrbbrrr..", ".rrrrbbrrrr."], ["....yyyy....", ".....kk.....", "...rrbbrr...", "..rrrbbrrr..", ".rrrrbbrrrr."]],
    besen: ["n...", "n...", "n...", "n...", "n...", "n...", "n...", "yyy.", "yyyy", "yyyy"],
    mopp: ["n...", "n...", "n...", "n...", "n...", "n...", "n...", "www.", "wwww", "w.w.w"],
    giesskanne: ["......s", ".sss.s.", "sssss..", "ssss...", ".ss...."],
    pflanze: [".e.e.", "eeeee", "..e..", "rrrrr", ".rrr."],
    paket: ["tttttttttt", "tNttttttNt", "tttttttttt", "tttNNNNttt", "tttttttttt"],
    handy: ["kkk", "kck", "kck", "kkk"],
    zeitung: ["wwwwwwwwww", "wkkkkwkkkw", "wwwwwwwwww", "wkkwkkkkkw", "wwwwwwwwww", "wkkkwkkwkw", "wwwwwwwwww"],
    buch: ["NNNNNNNNNN", "NwwwwNwwwN", "NwkkwNwkkN", "NwwwwNwwwN", "NwkkwNwkwN", "NNNNNNNNNN"],
    tuete: ["..k..k", "..k..k", "tttttt", "tttttt", "tNNttt", "tttttt"],
    gitarre: ["........NN", "........n.", ".......n..", "..yyyyn...", ".yyyyyy...", "yyykyyy...", "yyyyyyy...", ".yyyyy...."],
    turntable: ["kkkkkkkkkkkkkkkkkk", "kgggggkkkkkkgggggk", "kggkggkkrrkkggkggk", "kgggggkkkkkkgggggk", "kkkkkkkkkkkkkkkkkk"],
    kopfhoerer: ["...kkkkkkkkkk...", "..k..........k..", ".k............k.", "rr............rr", "rr............rr", "rr............rr"],
    trommel: ["wwwwwwwwwwww", "rrrrrrrrrrrr", "rzrrzrrzrrzr", "rrrrrrrrrrrr", ".k........k."],
    trompete: ["......z", "zzzzzzz", "zZ.zzzz", "......z"],
    klavier: ["kkkkkkkkkkkkkkkkkk", "kwkwwkwkwwkwkwwkwk", "kwwwwwwwwwwwwwwwwk", "kkkkkkkkkkkkkkkkkk", ".k..............k."],
    mikro: [".kk", "kGG", ".kk", "..k", "..k", "..k"],
    taktstock: ["w", "w", "w", "k"],
    hantel: ["kk..kk", "kkSSkk", "kk..kk"],
    ball: [".wk.", "wkww", "wwkw", ".kw."],
    basketball: [".oo.", "oOoo", "ooOo", ".oo."],
    boxR: ["rr", "rR", "rr"],
    boxL: ["rr", "Rr", "rr"],
    langhantel: ["kk....................kk", "kkSSSSSSSSSSSSSSSSSSSSkk", "kk....................kk"],
    laptop: ["..ssssssss..", "..sccccccs..", "..sccwwccs..", "..ssssssss..", "SSSSSSSSSSSS"],
    lupe: [".kk..", "kcck.", "kcck.", ".kk..", "...n.", "....n"],
    knopf: [".rrrr.", "rrWrrr", "kkkkkk", ".kkkk.", ".kkkk.", ".kkkk."],
    kaffee: ["rrr.", "rrrr", "rrr.", "rrr."],
    tafel: ["NNNNNNNNNNNNNNNN", "NEEEEEEEEEEEEEEN", "NEwwEEwEEwwwEEEN", "NEEEEwEEEEEEwEEN", "NEEwwwEEwwEEEEEN", "NEEEEEEEEEEEEEEN", "NNNNNNNNNNNNNNNN", ".N............N.", ".N............N.", ".N............N.", ".N............N."],
    zeiger: ["n", "n", "n", "n", "n"],
    block: ["yyyyy", "ykkky", "yyyyy", "ykkyy", "yyyyy"],
    stift: ["k", "y", "y", "y"],
    server: ["GGGGGGG", "GkvkkkG", "GGGGGGG", "GkkvkkG", "GGGGGGG", "GkrkkkG", "GGGGGGG", "G.....G", "GGGGGGG"],
    hammer: ["kkkk", "kkkk", ".n..", ".n..", ".n.."],
    schluessel: ["s.s", "sss", ".s.", ".s.", ".s."],
    staffelei: ["....N....", "..wwwww..", "..wlcmw..", "..wyrbw..", "..wwwww..", ".N..N..N.", "N...N...N"],
    pinsel: ["r", "n", "n", "n"],
    kolben: [["..s..", "..s..", ".sls.", "slllS", "slllS", ".sss."], ["..s..", "..s..", ".sls.", "sllsS", "slllS", ".sss."]],
    telefon: ["kkk", "k..", "k..", "kkk"],
    tee: ["wwww.", "wwwwk", "wwww.", ".ww.."],
    pizza: ["tttttt", "yryyry", ".yyry.", "..yy..", "..y..."],
    burger: [".tttt.", "tttttt", "llllll", "NNNNNN", "yyyyyy", "tttttt"],
    eis: [".mm.", "mmmm", "mwmm", ".tt.", ".tt.", "..t."],
    donut: [".mmm.", "mm.mm", "mt.tm", ".ttt."],
    schuessel: ["y.y.y.y", "yyyyyyy", "wwwwwww", ".wwwww."],
    apfel: ["..e.", ".rr.", "rrrr", "rrrr", ".rr."],
    popcorn: [".wyw.", "wywyw", "rwrwr", "rwrwr", ".rwr."],
    kuchen: ["...y....", "...r....", "...w....", "mmmmmmmm", "wwwwwwww", "mmmmmmmm", "wwwwwwww"],
    grill: ["kkkkkkkkkk", "kGkGkGkGkk", "krkrkrkrkk", "kkkkkkkkkk", ".k......k.", ".k......k.", ".k......k."],
    topf: ["k..........k", "GGGGGGGGGGGG", "GGGGGGGGGGGG", ".GGGGGGGGGG."],
    kelle: ["n", "n", "n", "G"],
    glas: ["w.w", "wyw", "wyw", ".w.", ".w.", "www"],
    controller: [".kkkkkkkk.", "kkrkkkkbkk", "kkkkkkkkkk", "kk......kk"],
    vrbrille: ["kkkkkkkkkkkkkk", "kGGGGGGGGGGGGk", "kGbbbGGGGbbbGk", "kkkkkkkkkkkkkk"],
    truhe: [".NNNNNNNN.", "NzzzzzzzzN", "NNNNzzNNNN", "NnnnnnnnnN", "NnnnnnnnnN", "NNNNNNNNNN"],
    truheOffen: ["NNNNNNNNNN", "NnnnnnnnnN", ".zyzyzyzy.", "NNNNNNNNNN", "NnnnnnnnnN", "NNNNNNNNNN"],
    schwert: [".s.", ".s.", ".s.", ".s.", ".s.", ".s.", "zzz", ".n.", ".n."],
    decke: ["bbbbbbbbbbbbbbbb", "bwbbwbbwbbwbbwbb", "bbbbbbbbbbbbbbbb", "bwbbwbbwbbwbbwbb", "bbbbbbbbbbbbbbbb"],
    sonnenbrille: [".kkkkk..kkkkk.", ".kkkkkkkkkkkk.", "..kkk....kkk.."],
    teddy: ["nn.nn", "nnnnn", "nknkn", "nntnn", ".nnn.", "nn.nn"],
    schneeball: [".w.", "wwS", ".S."],
    rechen: ["n...", "n...", "n...", "n...", "n...", "n...", "NNNNN", "N.N.N"],
    angel: ["...........k", ".........kk.", ".......kk...", ".....kk.....", "...kk.......", ".kk.........", "k..........."],
    blume: [".m.", "mym", ".m.", ".e.", "ee.", ".e."],
    katze: ["G...G..", "GG.GG..", "GkGkG..", "GGmGG.G", "GGGGGGG", ".G.G.G."],
    zauberstab: ["y", "k", "k", "k", "k"],
    kugel: [".cc.", "cWcc", "cccc", ".cc.", "NNNN"],
    laterne: [".k.", "kkk", "kyk", "kyk", "kkk"],
    karte: ["tttttttt", "tNtttNtt", "tttrtttt", "tNtttttN", "tttNtttt"],
    fernrohr: ["......kk", "....kkG.", "..kkG...", "kkG....."],
    geschenk: ["..r.r..", "...r...", "rrrrrrr", "yyyryyy", "yyyryyy", "yyyryyy"],
    pokal: ["z.zzz.z", "zzzzzzz", ".zzzzz.", "..zzz..", "...z...", ".zzzzz."],
    flagge: ["nrrrrrr", "nrrwrrr", "nrwwwrr", "nrrwrrr", "nrrrrrr", "n......", "n......", "n......", "n......"],
    kamera: ["..kk..", "kkkkkk", "kwkkGk", "kkkkkk"],
    stange: ["yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"],
    becher: ["LLL.", "LLLL", "LLL.", ".L.."],
    gluehbirne: [".yyy.", "yyyyy", ".yyy.", ".GGG."],
    lolli: [".mmm.", "mmwmm", ".mmm.", "..w..", "..w..", "..w.."],
    fackel: [[".y.", "yoy", ".o.", ".n.", ".n.", ".n."], ["y..", ".yo", ".o.", ".n.", ".n.", ".n."]],
    fernbedienung: ["kk", "kr", "kk", "kk"],
    stock2: ["zz", "k.", "k.", "k.", "k.", "k.", "k.", "k.", "k."],
    seifenblasen: ["kkk", "k.k", "kkk", ".n.", ".n."],
    fahneCH: ["nrrrrrr", "nrrwrrr", "nrwwwrr", "nrrwrrr", "nrrrrrr", "n......", "n......", "n......"],
    wuerfel: ["wwww", "wkww", "wwkw", "wwww"],
    schild: ["wwwwwwww", "wkkkkkkw", "wwwwwwww", "...n....", "...n....", "...n...."],
    kuehlschrank: ["ssssssss", "sSsssssS", "ssssssss", "sSsssssS", "ssssssss"],
    hotdog: [".tttttt.", "rrrrrrrr", ".tttttt."],
    sushi: [".www.", "wrrrw", "kkkkk"],
    brezel: [".nn.nn.", "n..n..n", ".nnnnn.", "..n.n.."],
    milch: [".ww.", "wwww", "wbbw", "wwww"],
    zeitungR: ["wwwwwwwwww", "wrrrrwkkkw", "wwwwwwwwww", "wkkwkkkkkw", "wwwwwwwwww"],
    koffer: [".nn.", "NNNN", "NnnN", "NNNN"],
    brett: ["nnnnnnnnnnnn", "NNNNNNNNNNNN"],
    kiste: ["nnnnnn", "nNnnNn", "nnnnnn", "nNnnNn", "nnnnnn"]
  };
})();
