(() => {
  const K = window.K;
  const L = [];
  const add = (n, slot, gruppe, m, extra) => L.push(Object.assign({ n, slot, gruppe, m }, extra || {}));
  const skin = (n, body, dark, light, extra) => L.push(Object.assign({ n, slot: "skin", gruppe: "Farben & Muster", body, dark, light }, extra || {}));

  skin("Klassisch Claude", "#d97757", "#b0573a", "#eb9b80");
  skin("Pastellrosa", "#f4a7bb", "#d9809a", "#fbc8d5");
  skin("Minze", "#8fd9bd", "#5fb597", "#b6ead6");
  skin("Himmelblau", "#86b9f0", "#5b92d1", "#b2d3f7");
  skin("Lavendel", "#b8a1e6", "#9076cc", "#d3c4f2");
  skin("Zitrone", "#f2dc5d", "#cfb62f", "#f8ea94");
  skin("Tomate", "#e5533d", "#b83a28", "#f07e6c");
  skin("Schiefer", "#7d8793", "#5b646f", "#a2abb5");
  skin("Schneeweiss", "#f2f0ea", "#cfcbc0", "#ffffff");
  skin("Mitternacht", "#2c3a66", "#1b2547", "#46558a");
  skin("OLED", "#050505", "#000000", "#1a1a1a", { eye: "#d97757" });
  skin("Gold", "#e6b422", "#a8781a", "#f7d974", { muster: (x, y, t) => ((x + y - Math.floor(t * 12)) % 16 === 0 ? "#fff6c8" : null) });
  skin("Silber", "#c3cad3", "#8f98a3", "#e3e8ee", { muster: (x, y, t) => ((x + y - Math.floor(t * 12)) % 16 === 0 ? "#ffffff" : null) });
  skin("Bronze", "#b87333", "#8a5222", "#d89a5f", { muster: (x, y, t) => ((x + y - Math.floor(t * 12)) % 16 === 0 ? "#f0c49a" : null) });
  skin("Smaragd", "#2fa36b", "#1d774b", "#5fc795");
  skin("Rubin", "#c21e4b", "#8e1235", "#e0527a");
  skin("Saphir", "#2552c7", "#173a93", "#5a82e0");
  skin("Amethyst", "#8a4fc9", "#633594", "#ae80dd");
  skin("Neonpink", "#ff3fa4", "#c4167a", "#ff85c6");
  skin("Neongrün", "#5cff5c", "#28c428", "#a3ffa3");
  skin("Karamell", "#d4913f", "#a96b24", "#e6b57a");
  skin("Schokolade", "#6b4226", "#4a2c18", "#8c5d3c");
  skin("Erdbeere", "#e8455f", "#b82b43", "#f07a8d", { muster: (x, y) => (y === 0 ? "#3e8f3b" : (x * 3 + y * 5) % 7 === 0 ? "#f5d03b" : null) });
  skin("Wassermelone", "#ec5a6a", "#3e8f3b", "#f58a96", { muster: (x, y, t, r) => (y >= r.bh - 2 ? "#3e8f3b" : y === r.bh - 3 ? "#e8f5d8" : (x * 5 + y * 3) % 9 === 0 ? "#1b1a18" : null) });
  skin("Tiger", "#f28c28", "#b85f10", "#f7b36b", { muster: (x, y) => ((x + (y % 3 === 0 ? 1 : 0)) % 5 === 0 ? "#1b1a18" : null) });
  skin("Leopard", "#e3b35f", "#b88a3a", "#f0cf8f", { muster: (x, y) => ((x * 7 + y * 11) % 13 === 0 ? "#3b2a17" : (x * 7 + y * 11) % 13 === 1 ? "#8a5a22" : null) });
  skin("Kuh", "#f4f1e8", "#c8c4b8", "#ffffff", { muster: (x, y) => ((x > 1 && x < 6 && y > 1 && y < 5) || (x > 8 && x < 12 && y > 4 && y < 8) ? "#1b1a18" : null) });
  skin("Tarnfarbe", "#6b7d45", "#4d5a31", "#8a9c5f", { muster: (x, y) => { const n = K.rnd(Math.floor(x / 3) * 17 + Math.floor(y / 2) * 5); return n < 0.3 ? "#3f4a26" : n < 0.55 ? "#8f7e4f" : null; } });
  skin("Regenbogen", "#d9443a", "#8e241f", "#f28c28", { muster: (x, y, t) => ["#d9443a", "#f28c28", "#f5d03b", "#86c95c", "#3a6fd6", "#9b61d3"][(y + Math.floor(t * 6)) % 6] });
  skin("Holografisch", "#b8a1e6", "#9076cc", "#d3c4f2", { muster: (x, y, t) => `hsl(${Math.round((x * 12 + y * 8 + t * 120) % 360)}, 75%, 70%)` });
  skin("Galaxie", "#1b1640", "#0d0a24", "#2e2766", { muster: (x, y, t) => { const n = K.rnd(x * 13 + y * 7); return n > 0.93 && Math.sin(t * 4 + n * 50) > 0 ? "#ffffff" : n > 0.85 ? "#9b61d3" : null; } });
  skin("Lava", "#c23b16", "#7a1f08", "#f28c28", { muster: (x, y, t) => (Math.sin(x * 0.7 + y * 0.9 + t * 3) > 0.55 ? "#f5d03b" : Math.sin(x * 0.4 - y * 0.6 + t * 2) > 0.3 ? "#f28c28" : null) });
  skin("Eis", "#bfe6f5", "#84c3dc", "#e6f7fd", { muster: (x, y) => ((x * 3 + y * 7) % 11 === 0 ? "#ffffff" : null) });
  skin("Geist", "#f2f0ea", "#c8c4b8", "#ffffff", { alpha: 0.55 });
  skin("Drahtgitter", "#d97757", "#d97757", "#d97757", { umriss: true });
  skin("Gameboy", "#8bac0f", "#306230", "#9bbc0f", { eye: "#0f380f", muster: (x, y) => (y === 0 ? "#9bbc0f" : null) });
  skin("Einheit 01", "#6b3fa0", "#3f2266", "#8e62c4", { muster: (x, y, t, r) => (x === 1 || x === r.bw - 2 ? "#86e05a" : y === 2 && x > 4 && x < 9 ? "#f28c28" : null) });
  skin("Einheit 02", "#c8281e", "#8a1810", "#e5533d", { muster: (x, y, t, r) => (y === 1 ? "#f28c28" : x === 0 || x === r.bw - 1 ? "#1b1a18" : null) });
  skin("Einheit 00", "#e8e6df", "#9aa3ad", "#ffffff", { muster: (x, y, t, r) => (y < 2 ? "#2552c7" : x < 2 || x > r.bw - 3 ? "#2552c7" : null) });
  skin("Schweizerkreuz", "#d52b1e", "#9e1d13", "#e85a4f", { muster: (x, y, t, r) => { const cx = r.bw / 2 - 0.5, cy = r.bh / 2 - 0.5; return (Math.abs(x - cx) < 1.1 && Math.abs(y - cy) < 3.1) || (Math.abs(y - cy) < 1.1 && Math.abs(x - cx) < 3.1) ? "#ffffff" : null; } });
  skin("Holz", "#b07a45", "#7d5329", "#c99762", { muster: (x, y) => (Math.sin(y * 1.3 + Math.sin(x * 0.5) * 1.5) > 0.6 ? "#8a5a2c" : null) });
  skin("Marmor", "#ece8df", "#bdb6a8", "#ffffff", { muster: (x, y) => (Math.abs(Math.sin(x * 0.45 + y * 0.9) + Math.sin(y * 0.3)) < 0.18 ? "#8b877d" : null) });
  skin("Terminal", "#0b0f0b", "#000000", "#1a241a", { eye: "#34e8a8", muster: (x, y, t) => (y % 2 === 0 && K.rnd(x * 3 + y + Math.floor(t * 4) * 17) > 0.72 ? "#1f8f5a" : null) });
  skin("Sonnenuntergang", "#f28c28", "#8e241f", "#f5d03b", { muster: (x, y, t, r) => ["#f5d03b", "#f7b33b", "#f28c28", "#ec6a3a", "#d9443a", "#b8305a", "#8a2a6a", "#5b3290", "#3b2470"][Math.min(8, Math.floor((y / r.bh) * 9))] });

  const kopf = (n, m, extra) => add(n, "kopf", "Kopf", m, extra);
  kopf("Wanderhut", ["....NNNNNNNN....", "...NnnnnnnnnN...", "...NNNNNNNNNN...", "NNNNNNNNNNNNNNNN"]);
  kopf("Zylinder", ["..kkkkkkkkkk..", "..kkkkkkkkkk..", "..kkkkkkkkkk..", "..krrrrrrrrk..", "kkkkkkkkkkkkkk"]);
  kopf("Krone", ["z..z..zz..z..z", "zz.zz.zz.zz.zz", "zzzzzzzzzzzzzz", "zrzzbzzzzbzzrz"]);
  kopf("Zauberhut", [".........PP...", ".......PPP....", "......PPPP....", ".....PPyPPP...", "....PPPPPPPP..", "...PPPPyPPPPP.", "PPPPPPPPPPPPPP"]);
  kopf("Cowboyhut", ["....nnnnnnnn....", "...nnnNNnnnnn...", "n..nnnnnnnnnn..n", "nnnnnnnnnnnnnnnn", ".nnnnnnnnnnnnnn."]);
  kopf("Piratenhut", ["...kkkkkkkkkk...", "..kkkkkwwkkkkk..", ".kkkkkwkkwkkkkk.", "kkkkkkkwwkkkkkkk", "kkkkkkkkkkkkkkkk"]);
  kopf("Kochmütze", ["..wwww..wwww..", ".wwwwwwwwwwwww.", ".wwwwwwwwwwwww.", "..wwwwwwwwwww..", "..LLLLLLLLLLL.."]);
  kopf("Partyhut", ["......yy......", "......mm......", ".....myym.....", ".....ymmy.....", "....mymmym....", "....ymyymy...."]);
  kopf("Propellermütze", [["..yyyyyyyyyy..", "......kk......", "....rrbbrr....", "...rrrbbrrr...", "..rrrrbbrrrr.."], [".....yyyy.....", "......kk......", "....rrbbrr....", "...rrrbbrrr...", "..rrrrbbrrrr.."]], { fps: 12 });
  const beanie = ["......ww......", ".....wwww.....", "...11111111...", "..1111111111..", "..2222222222.."];
  kopf("Mütze rot", beanie, { c1: "#d9443a", c2: "#8e241f" });
  kopf("Mütze grau", beanie, { c1: "#8b877d", c2: "#55524b" });
  kopf("Mütze senfgelb", beanie, { c1: "#d6a728", c2: "#a17a14" });
  kopf("Mütze tannengrün", beanie, { c1: "#2f7a45", c2: "#1d5230" });
  const cap = ["...111111.....", "..11111111....", "..111111112222"];
  kopf("Cap rot", cap, { c1: "#d9443a", c2: "#8e241f" });
  kopf("Cap blau", cap, { c1: "#3a6fd6", c2: "#1d3b8c" });
  kopf("Cap schwarz", cap, { c1: "#1b1a18", c2: "#55524b" });
  kopf("Cap rückwärts", [".....111111...", "....11111111..", "222211111111.."], { c1: "#86c95c", c2: "#3e8f3b" });
  kopf("Heiligenschein", ["...yyyyyyyy...", "..y........y..", "...yyyyyyyy..."], { oy: -3 });
  kopf("Teufelshörner", ["r............r", "rr..........rr", ".rr........rr."]);
  kopf("Hasenohren", [".wmw......wmw.", ".wmw......wmw.", ".wmw......wmw.", ".wmw......wmw.", ".www......www."]);
  kopf("Katzenohren", [".k..........k.", "kmk........kmk", "kkkk......kkkk"]);
  kopf("Fuchsohren", [".o..........o.", "ooo........ooo", "owoo......oowo"]);
  kopf("Antennen", ["..v........v..", "...k......k...", "....k....k...."]);
  kopf("Blume im Haar", ["..........mym.", "...........m..", "...........e.."]);
  kopf("Schleife", ["..........mm.m", "..........mmmm", "..........m.mm"]);
  kopf("Kopfhörer", K.PROPS.kopfhoerer, { oy: 3 });
  kopf("Kopfhörer weiss", ["...wwwwwwwwww...", "..w..........w..", ".w............w.", "ww............ww", "ww............ww", "ww............ww"], { oy: 3 });
  kopf("Stirnband rot", ["11111111111111"], { oy: 2, c1: "#d9443a" });
  kopf("Stirnband Frottee", ["1w1w1w1w1w1w1w"], { oy: 2, c1: "#3a6fd6" });
  kopf("Ninja-Band", ["kkkkkkkkkkkkkkkk", "..............kk", "...............k"], { oy: 4 });
  kopf("Bauhelm", ["....yyyyyyyy....", "..yyyyyyyyyyyy..", ".yyyyyyyyyyyyyy.", "yyyyyyyyyyyyyyyy"]);
  kopf("Feuerwehrhelm", ["....rrrrrrrr....", "..rrrrzzrrrrrr..", ".rrrrrzzrrrrrrr.", "rrrrrrrrrrrrrrrr", "kkkkkkkkkkkkkkkk"]);
  kopf("Wikingerhelm", ["w..............w", "ww....SSSS....ww", ".wwSSSSSSSSSSww.", "...SSSSSSSSSS...", "..SSSSSSSSSSSS..", "..SzSzSzSzSzSS.."]);
  kopf("Ritterhelm", ["...SSSSSSSS...", "..SSSSSSSSSS..", ".SSSSSSSSSSSS.", "SSSSSSSSSSSSSS", "SSSSSSSSSSSSSS", "SkkkkkSSkkkkkS", "SSSSSSSSSSSSSS", "SSSSSSSSSSSSSS"], { oy: 4 });
  kopf("Raumhelm", ["....cccccccc....", "..cc........cc..", ".c..W.........c.", "c.W............c", "c..............c", "c..............c", "c..............c", "c..............c", "c..............c"], { oy: 7 });
  kopf("Detektivmütze", ["....nNnNnN....", "...NnNnNnNnN..", "..nNnNnNnNnNn.", "NnNnNnNnNnNnNn"]);
  kopf("Baskenmütze", ["......k.......", "...rrrrrrrr...", "..rrrrrrrrrrr.", ".rrrrrrrrrrrr."]);
  kopf("Sombrero", ["........yyyy........", ".......yyyyyy.......", ".......yrrrry.......", "yyyyyyyyyyyyyyyyyyyy", ".yyyyyyyyyyyyyyyyyy."]);
  kopf("Doktorhut", ["kkkkkkkkkkkkkkkk", "....kkkkkkkk.y..", "....kkkkkkkk.y..", ".............y.."]);
  kopf("Einhorn-Horn", ["......yw......", "......wy......", ".....ywyw.....", ".....wywy....."]);
  kopf("Pilzhut", ["....rrrrrr....", "..rrwrrrrwrr..", ".rrrrrrwwrrrr.", "rrwwrrrrrrrwrr"]);
  kopf("Fischerhut", ["...eeeeeeee...", "...eeeeeeee...", ".eeeeeeeeeeee."]);
  kopf("Weihnachtsmütze", ["..........ww..", "........rrww..", "......rrrr....", "....rrrrrr....", "..rrrrrrrrrr..", "wwwwwwwwwwwwww"]);
  kopf("Hexenhut", [".....kk.......", "....kkk.......", "...kkkkk......", "...kkpkkk.....", "..kkkkkkkk....", "kkkkkkkkkkkkkk"]);
  kopf("Blumenkranz", ["m.y.m.y.m.y.m.", ".eeeeeeeeeeee."]);
  kopf("Lorbeerkranz", ["z.z.z....z.z.z", ".zzzz....zzzz."]);
  kopf("Kopfverband", ["wwwwwwwwwwwwww", "..........rw.."], { oy: 2 });
  kopf("Irokese pink", ["......mm......", "......mm......", ".....mmmm.....", "......mm......"]);
  kopf("Irokese grün", ["......ll......", "......ll......", ".....llll.....", "......ll......"]);
  kopf("Wuschelhaare braun", ["..N.NN.N.N....", ".NNNNNNNNNNN..", "NNNNNNNNNNNNNN"]);
  kopf("Wuschelhaare blond", ["..z.zz.z.z....", ".zzzzzzzzzzz..", "zzzzzzzzzzzzzz"]);
  kopf("Matrosenmütze", ["...wwwwwwww...", "..wwwwwwwwww..", "..bbbbbbbbbb.."]);
  kopf("Tell-Apfel", ["......e.......", ".....rrr......", "....rrrrr.....", "....rrrrr.....", ".....rrr......"]);
  kopf("Sennenkäppi", ["....kkkkkk....", "...kkkkkkkk...", "..kkkkkkkkkk..", "..rrrrrrrrrr.."]);
  kopf("Drachenhörner", ["P............P", "PP..........PP", ".PP........PP.", "..P........P.."]);

  const augen = (n, m, extra) => add(n, "augen", "Augen", m, extra);
  augen("Sonnenbrille", K.PROPS.sonnenbrille, { oy: 0 });
  augen("Pilotenbrille", [".zzzzz..zzzzz.", "zkkkkkzzkkkkkz", ".zkkkz..zkkkz."]);
  augen("Nerdbrille", [".kkkkk..kkkkk.", ".k...kkkk...k.", ".kkkkk..kkkkk."]);
  augen("Runde Brille", ["..kkk....kkk..", ".k...kkkk...k.", "..kkk....kkk.."]);
  augen("Herzbrille", [".m.m....m.m...", "mmmmmkkmmmmm..", ".mmm....mmm..."], { ox: 1 });
  augen("Sternbrille", [".y.y....y.y...", "yyyyykkyyyyy..", ".y.y....y.y..."], { ox: 1 });
  augen("3D-Brille", ["kkkkkkkkkkkkkk", "krrrrkkkkcccck", "kkkkkkkkkkkkkk"]);
  augen("Monokel", [".........zzz..", "........z...z.", ".........zzz..", "...........z..", "...........z.."]);
  augen("Augenklappe", ["kkkkkkkkkkkkkk", ".kkkk.........", "..kk.........."]);
  augen("Skibrille", ["11111111111111", "1oooooooooooo1", "1oooooooooooo1", "11111111111111"], { c1: "#d9443a" });
  augen("Taucherbrille", ["kkkkkkkkkkkkkk", "kccccckkccccck", "kccccckkccccck", "kkkkkkkkkkkkkk"]);
  augen("VR-Brille", K.PROPS.vrbrille);
  augen("Pixel-Brille", ["kkkkkkkkkkkkkk", ".kwkkk..kwkkk.", "..kkk....kkk.."]);
  augen("Steampunk-Brille", [".nnnnn..nnnnn.", "nzcczznnzcczzn", "nzcczzn.zcczzn", ".nnnnn..nnnnn."]);
  augen("Cyber-Visier", [["xxxxxxxxxxxxxx", "xuuuuuuuuuuuux", "xxxxxxxxxxxxxx"], ["xxxxxxxxxxxxxx", "xuuWuuuuuuuuux", "xxxxxxxxxxxxxx"], ["xxxxxxxxxxxxxx", "xuuuuuuuuWuuux", "xxxxxxxxxxxxxx"]], { fps: 6 });
  augen("Nachtsicht", [".kkkkk..kkkkk.", "kkvvvkkkkvvvkk", ".kkkkk..kkkkk."]);

  const gesicht = (n, m, extra) => add(n, "gesicht", "Gesicht", m, extra);
  gesicht("Clownnase", ["rr", "rr"]);
  gesicht("Wangenröte", ["mm........mm"]);
  gesicht("Pflaster", ["..........tt", ".........ttt", "........ttt."], { oy: -2 });
  gesicht("Vampirzähne", ["kkkk", "w..w"], { oy: 1 });
  gesicht("Zunge raus", ["kkkk", ".mm.", ".mm."], { oy: 1 });

  const hals = (n, m, extra) => add(n, "hals", "Hals", m, extra);
  const fliege = ["11.11", "11111", "11.11"];
  hals("Fliege schwarz", fliege, { c1: "#1b1a18" });
  hals("Fliege rot", fliege, { c1: "#d9443a" });
  hals("Fliege gepunktet", ["1w.1w", "11111", "w1.w1"], { c1: "#3a6fd6" });
  const krawatte = ["111", ".1.", "121", "111", ".1."];
  hals("Krawatte rot", krawatte, { c1: "#d9443a", c2: "#8e241f" });
  hals("Krawatte blau", krawatte, { c1: "#3a6fd6", c2: "#1d3b8c" });
  hals("Krawatte gestreift", ["121", ".2.", "212", "121", ".1."], { c1: "#f5d03b", c2: "#1b1a18" });
  const schal = ["1212121212121212", "2121212121212121", "..............12", "..............21"];
  hals("Schal grün", schal, { c1: "#3e8f3b", c2: "#86c95c", oy: -1 });
  hals("Schal blau", schal, { c1: "#1d3b8c", c2: "#3a6fd6", oy: -1 });
  hals("Goldkette", ["z..........z", ".z........z.", "..zzzzzzzz..", ".....zz....."], { oy: -1 });
  hals("Perlenkette", ["w..........w", ".w........w.", "..w.w.w.w...", "....."], { oy: -1 });
  hals("Medaille", ["r..........b", ".r........b.", "..r......b..", "....zzzz....", "....zZZz....", ".....zz....."], { oy: -2 });

  const koerper = (n, m, extra) => add(n, "koerper", "Kleidung", m, extra);
  koerper("Anzug", ["..............", "..............", "..............", "..............", "kkkkkwrwkkkkkk", "kkkkkwrwkkkkkk", "kkkkkkrkkkkkkk", "kkkkkkkkkkkkkk", "kkkkkkkkkkkkkk"]);
  koerper("Trikot 10", ["..............", "..............", "..............", "..............", "rrrrrrrrrrrrrr", "rrrrwwrwwwrrrr", "rrrrrwrwrwrrrr", "rrrrrwrwwwrrrr", "wwwwwwwwwwwwww"]);
  koerper("Smoking", ["..............", "..............", "..............", "..............", "kkkkwwkwwkkkkk", "kkkkwwwwwkkkkk", "kkkkkwkwkkkkkk", "kkkkkkkkkkkkkk", "kkkkkkkkkkkkkk"]);

  const ruecken = (n, m, extra) => add(n, "ruecken", "Rücken", m, extra);

  const hand = (n, m, extra) => add(n, "hand", "Hand", m, extra);

  const aura = (n, fx) => add(n, "aura", "Aura", null, { fx });

  const zaehler = {};
  L.forEach((z) => {
    const basis = z.n.toLowerCase().replace(/ä/g, "ae").replace(/ö/g, "oe").replace(/ü/g, "ue").replace(/ß/g, "ss").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
    zaehler[basis] = (zaehler[basis] || 0) + 1;
    z.id = "a-" + basis + (zaehler[basis] > 1 ? "-" + zaehler[basis] : "");
  });
  K.AUSSEHEN = L;
})();
